id: P010638
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W18126
  title: ལུས་བསྲུང་རྡོ་རྗེ་ཕ་ལམ
  author: ''
  volumes:
    30b06b3f4c4e4b09a70f36391c8233fb:
      image_group_id: I4891
      title: ''
      volume_number: 1
      total_pages: 182
      base_file: v001.txt
